### ISSUE TITLE
使用SQL注入 并且成功了

### ISSUE THREAD

**Issue by george-jiang-wow** [oiso-developer-team/OISO-frontend#1]
如题。希望开发团队能在开发之余注意下安全问题。

**Comment by diyanqi** [comment]
望发我份邮件描述一下具体方法。我在安全这方面不太了解🤣

**Comment by diyanqi** [comment]
已在此更新中修复，包括前端与后端：
https://github.com/oiso-developer-team/OISO-frontend/commit/7414368a0ea752c1af3921a6bb39724424dbab8f
