### ISSUE TITLE
请求前端实现：打卡&积分系统

### ISSUE THREAD

**Issue by diyanqi** [oiso-developer-team/OIso-frontend#15]
如题，后端已完成api接口：

### 1. 获取我的积分
地址：https://online.oiso.cf/rewards/getmine
请求方式：`GET`
要求携带 cookies 来确定身份。
返回值：一个字符串数字。
- 示例返回：
```
3
```
注：不管是不是第一次使用rewards，或者积分为0，都会返回一个字符串数字，不必担心。

### 2. 每日打卡
地址：https://online.oiso.cf/rewards/dk
请求方式：`GET`
要求携带 cookies 来确定身份。
返回值：`解析好的json` 或 `429 Too Many Requests 错误`。
- 示例返回1：
```json
{"code":200,"msg":"打卡成功"}
```
- 示例返回2：
```
Too Many Requests
1 per 1 day
```
注：由于限制一天打卡一次的方案是限制请求数量为1天1次，故如果当前服务器重启程序了，会导致可以多次打卡。每次打卡增加3积分。

**Comment by diyanqi** [comment]
以后我就搞后端了，前端麻烦你们写一下了（逃

**Comment by diyanqi** [comment]
还是我自己做了qwq
https://github.com/oiso-developer-team/OIso-frontend/commit/cc9a54a44f42513b925e0f2737f1c84f27d2243e

**Comment by george-jiang-wow** [comment]
啊这，我刚想开始学JS来着（
