### ISSUE TITLE
请求添加opensearch套件支持

### ISSUE THREAD

**Issue by NFLSCode** [oiso-developer-team/OIso-frontend#16]
相关文档：https://developer.mozilla.org/en-US/docs/Web/OpenSearch

好处：浏览器可添加一个“使用xx搜索”，支持chrome，safari，firefox，edge。

**Comment by NFLSCode** [comment]
> > 相关文档：https://developer.mozilla.org/en-US/docs/Web/OpenSearch
> > 好处：浏览器可添加一个“使用xx搜索”，支持chrome，safari，firefox，edge。
> 
> 抱歉，开发者都在准备中考sweat_smile
> 
> 能否提供一个 Pr 捏

我也在准备中考 :sweat_smile:

**Comment by diyanqi** [comment]
6

**Comment by diyanqi** [comment]
已完成。
